# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main, master]

name: R-CMD-check

jobs:
  prepare-ptaxsim:
    uses: ./.github/workflows/prepare-ptaxsim.yaml
    secrets: inherit

  R-CMD-check:
    needs: prepare-ptaxsim
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release'}
          - {os: windows-latest,  r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PTAXSIM_DB_PATH: ${{ github.workspace }}/ptaxsim.db
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Restore database cache
        uses: actions/cache/restore@v3.3.1
        with:
          path: ptaxsim.db.bz2
          key: ${{ format('{0}-{1}', needs.prepare-ptaxsim.outputs.PTAXSIM_VERSION, hashFiles('DESCRIPTION')) }}
          fail-on-cache-miss: true
          enableCrossOsArchive: true

      - name: Unpack database (*nix)
        if: runner.os != 'Windows'
        run: bzip2 -d ptaxsim.db.bz2
        shell: bash

      - name: Unpack database (Windows)
        if: runner.os == 'Windows'
        run: 7z x ptaxsim.db.bz2
        shell: cmd

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
